version: "3.1"
services:
  express:
    build: .
    restart: always
    ports:
      - 80:3000
    working_dir: /usr/app
    volumes:
      - ./.env:/usr/app/.env
    command: npm run start
    networks:
      - my_presensi

networks:
  my_presensi: