version: "3.1"
services:
  express:
    build: .
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./dist:/usr/app/dist
      - .env:/usr/app/.env
    working_dir: /usr/app
    command: npm run start