version: "3.5"
services:
  express:
    build: .
    restart: always
    ports:
      - 80:3000
    volumes:
      - ./.env:/usr/app/.env
    command: npm run start --prefix /usr/app
    networks:
      - my-presensi

networks:
  my-presensi:
    name: my_presensi